export const SET_MOVIES_LIST = 'SET_MOVIES_LIST'
export const SET_SEARCH_MOVIES_LIST = 'SET_SEARCH_MOVIES_LIST'
export const CLEAR_MOVIES_LIST = 'CLEAR_MOVIES_LIST'
export const CLEAR_SEARCH_MOVIES_LIST = 'CLEAR_SEARCH_MOVIES_LIST'